# Generated by Django 4.2.20 on 2025-04-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_hash',
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
    ]
